version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: central_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: central_mayorista
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d

  clickhouse:
    image: clickhouse/clickhouse-server:24.3
    container_name: central_clickhouse
    restart: unless-stopped
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: central_analytics
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin123
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse/init:/docker-entrypoint-initdb.d

  grafana:
    image: grafana/grafana:11.0.0
    container_name: central_grafana
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin123
      GF_INSTALL_PLUGINS: grafana-clickhouse-datasource
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - clickhouse

volumes:
  postgres_data:
  clickhouse_data:
  grafana_data: